#!/usr/bin/env python3
"""Canonical source catalog shared by collectors, health checks, and metadata."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional


DEFAULT_BROWSER_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/120.0.0.0 Safari/537.36"
)

HEADER_PROFILES: Dict[str, Dict[str, str]] = {
    "default": {},
    "reddit": {
        "User-Agent": (
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 "
            "DailyTrendingBot/1.0"
        ),
        "Accept": "application/rss+xml, application/xml;q=0.9, */*;q=0.8",
    },
    "cmmc_reddit": {
        "User-Agent": (
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 "
            "CMMCWatch/1.0"
        ),
        "Accept": "application/rss+xml, application/xml;q=0.9, */*;q=0.8",
    },
    # Breaking Defense blocks some automated user agents but allows simple browser-like strings.
    "breaking_defense": {
        "User-Agent": "Mozilla/5.0",
        "Accept": "application/rss+xml, application/xml;q=0.9, */*;q=0.8",
    },
}

# Transport tuning used by both runtime collection and health checks.
DOMAIN_FETCH_PROFILES: Dict[str, Dict[str, object]] = {
    "feeds.washingtonpost.com": {
        "attempts": 3,
        "retry_delay": 0.8,
        "timeout": 20.0,
    },
    "breakingdefense.com": {
        "attempts": 2,
        "retry_delay": 0.6,
        "headers_profile": "breaking_defense",
        "timeout": 15.0,
    },
}


@dataclass(frozen=True)
class SourceSpec:
    key: str
    name: str
    url: str
    category: str
    kind: str  # rss | json | html
    source_key: Optional[str] = None  # Trend.source key
    collector: Optional[str] = None
    selector: Optional[str] = None
    json_count_path: Optional[str] = None
    timeout_seconds: Optional[float] = None
    headers_profile: str = "default"
    fallback_url: Optional[str] = None
    tier: int = 4
    source_type: str = "other"
    risk: str = "medium"
    language: str = "en"
    parser: str = "rss"
    healthcheck: bool = True


def _rss(
    key: str,
    name: str,
    url: str,
    category: str,
    collector: str,
    *,
    source_key: Optional[str] = None,
    timeout_seconds: Optional[float] = None,
    headers_profile: str = "default",
    fallback_url: Optional[str] = None,
    tier: int = 2,
    source_type: str = "news",
    risk: str = "low",
    parser: str = "rss",
) -> SourceSpec:
    return SourceSpec(
        key=key,
        name=name,
        url=url,
        category=category,
        kind="rss",
        source_key=source_key or key,
        collector=collector,
        timeout_seconds=timeout_seconds,
        headers_profile=headers_profile,
        fallback_url=fallback_url,
        tier=tier,
        source_type=source_type,
        risk=risk,
        parser=parser,
    )


def _json(
    key: str,
    name: str,
    url: str,
    category: str,
    *,
    source_key: Optional[str] = None,
    collector: Optional[str] = None,
    json_count_path: Optional[str] = None,
    tier: int = 3,
    source_type: str = "community",
    risk: str = "low",
    fallback_url: Optional[str] = None,
) -> SourceSpec:
    return SourceSpec(
        key=key,
        name=name,
        url=url,
        category=category,
        kind="json",
        source_key=source_key,
        collector=collector,
        json_count_path=json_count_path,
        fallback_url=fallback_url,
        tier=tier,
        source_type=source_type,
        risk=risk,
        parser="json_api",
    )


def _html(
    key: str,
    name: str,
    url: str,
    category: str,
    *,
    source_key: Optional[str] = None,
    collector: Optional[str] = None,
    selector: Optional[str] = None,
    tier: int = 3,
    source_type: str = "reference",
    risk: str = "low",
    fallback_url: Optional[str] = None,
) -> SourceSpec:
    return SourceSpec(
        key=key,
        name=name,
        url=url,
        category=category,
        kind="html",
        source_key=source_key,
        collector=collector,
        selector=selector,
        fallback_url=fallback_url,
        tier=tier,
        source_type=source_type,
        risk=risk,
        parser="html_scrape",
    )


# Canonical collector inputs.
COLLECTOR_SOURCES: List[SourceSpec] = [
    _rss(
        "ai",
        "AI 开发者日报",
        "https://ainews.liduos.com/rss.xml",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "anthropic_news",
        "Anthropic News",
        "https://rsshub.bestblogs.dev/anthropic/news",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "apple_machine_learning_research",
        "Apple Machine Learning Research",
        "https://machinelearning.apple.com/rss.xml",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "artificial_intelligence",
        "Artificial Intelligence",
        "https://aws.amazon.com/blogs/amazon-ai/feed/",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "cs_cl_updates_on_arxiv_org",
        "cs.CL updates on arXiv.org",
        "https://export.arxiv.org/rss/cs.CL",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "deepseek",
        "DeepSeek",
        "https://wechat2rss.bestblogs.dev/feed/1709da4f538d4ce4fb6d7a8ba1a5a1c297919601.xml",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "google_deepmind_news",
        "Google DeepMind News",
        "https://deepmind.com/blog/feed/basic/",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "hugging_face___blog",
        "Hugging Face - Blog",
        "https://huggingface.co/blog/feed.xml",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "mit_news___artificial_intelligence",
        "MIT News - Artificial intelligence",
        "https://news.mit.edu/rss/topic/artificial-intelligence2",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "openai_news",
        "OpenAI News",
        "https://openai.com/news/rss.xml",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "simon_willison_s_weblog",
        "Simon Willison's Weblog",
        "https://simonwillison.net/atom/everything/",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "the_latest_research_from_google",
        "The latest research from Google",
        "https://research.google/blog/rss/",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_012",
        "我爱计算机视觉",
        "https://wechat2rss.xlab.app/feed/b81ffcfff1107b5265cd7e39de610dc7ca72caf4.xml",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_013",
        "新智元",
        "https://wechat2rss.xlab.app/feed/ede30346413ea70dbef5d485ea5cbb95cca446e7.xml",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_014",
        "智谱",
        "https://wechat2rss.bestblogs.dev/feed/433d2134dca54d80804daf32e8be546155be3300.xml",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_015",
        "机器之心",
        "https://wechat2rss.bestblogs.dev/feed/8d97af31b0de9e48da74558af128a4673d78c9a3.xml",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_016",
        "腾讯混元",
        "https://wechat2rss.bestblogs.dev/feed/306ce19a1ca590c9c2df781789e828d1acfa1356.xml",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_017",
        "通义实验室",
        "https://wechat2rss.bestblogs.dev/feed/4ebee6222ae08705b8aabc9116f0defbcb6b17c6.xml",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_018",
        "量子位",
        "https://www.qbitai.com/feed",
        "ai",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "abyss",
        "Abyss的小屋",
        "https://www.rsnocsi.cn/feed",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "amiya",
        "Amiya的书桌",
        "https://blog.sayori.org/rss.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "android_performance",
        "Android Performance",
        "https://www.androidperformance.com/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "bboysoul_s_blog",
        "Bboysoul's Blog",
        "https://www.bboy.app/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "canva___engineering_blog",
        "Canva - Engineering Blog",
        "https://www.canva.dev/blog/engineering/feed.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "databricks",
        "Databricks",
        "https://www.databricks.com/feed",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "elastic_blog___elasticsearch__kibana__an",
        "Elastic Blog - Elasticsearch, Kibana, and ELK Stack",
        "https://www.elastic.co/blog/feed",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "engineering_at_slack",
        "Engineering at Slack",
        "https://slack.engineering/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "eric_s_blog",
        "Eric's Blog",
        "https://wsdjeg.net/feed.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "etsy_engineering___code_as_craft",
        "Etsy Engineering | Code as Craft",
        "https://codeascraft.com/feed/atom/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "freecodecamp_programming_tutorials__pyth",
        "freeCodeCamp Programming Tutorials: Python, JavaScript, Git & More",
        "https://www.freecodecamp.org/news/rss/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "icodex_______________react_typescript_ai",
        "icodex | 前端技术博客 | 专注 React、TypeScript、AI 与性能优化 Blog",
        "https://icodex.me/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "laike9m_s_blog",
        "laike9m's blog",
        "https://laike9m.com/blog/rss/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "liesauer_s_blog",
        "LiesAuer's Blog",
        "https://www.liesauer.net/blog/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "mactalk______blog",
        "MacTalk-池建强的 Blog",
        "http://macshuo.com/?feed=rss2",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "martin_fowler",
        "Martin Fowler",
        "https://martinfowler.com/feed.atom",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "microsoft_azure_blog",
        "Microsoft Azure Blog",
        "https://azure.microsoft.com/en-us/blog/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "netflix_techblog___medium",
        "Netflix TechBlog - Medium",
        "https://netflixtechblog.com/feed",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "nicksxs_s_blog",
        "Nicksxs's Blog",
        "https://nicksxs.me/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "node_js_blog",
        "Node.js Blog",
        "https://nodejs.org/en/feed/blog.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "obaby______void",
        "obaby 𝐢‍𝐧⃝ void",
        "https://h4ck.org.cn/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "onev_s_den",
        "OneV's Den",
        "https://onevcat.com/feed.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "pseudoyu",
        "pseudoyu",
        "https://www.pseudoyu.com/zh/index.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "python_insider",
        "Python Insider",
        "https://blog.python.org/feeds/posts/default",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "rust_blog",
        "Rust Blog",
        "https://blog.rust-lang.org/feed.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "rxliuli_blog",
        "rxliuli blog",
        "https://blog.rxliuli.com/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "ryanuo",
        "RYANUO",
        "https://ryanuo.cc/sitemap.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "seven_s_blog",
        "Seven's blog",
        "https://blog.diqigan.cn/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "sjdhome",
        "sjdhome",
        "https://sjdhome.com/blog/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "smallyu",
        "smallyu的博客",
        "https://smallyu.net/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "spotify_engineering",
        "Spotify Engineering",
        "https://engineering.atspotify.com/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "stack_overflow_blog",
        "Stack Overflow Blog",
        "https://blog.stackoverflow.com/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "stripe_blog",
        "Stripe Blog",
        "https://stripe.com/blog/feed.rss",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "supabase_blog",
        "Supabase Blog",
        "https://supabase.com/rss.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "taxodium",
        "Taxodium",
        "https://taxodium.ink/rss.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "the_airbnb_tech_blog___medium",
        "The Airbnb Tech Blog - Medium",
        "https://medium.com/feed/airbnb-engineering",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "the_cloudflare_blog",
        "The Cloudflare Blog",
        "https://blog.cloudflare.com/rss",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "the_github_blog",
        "The GitHub Blog",
        "https://github.blog/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "the_jetbrains_blog",
        "The JetBrains Blog",
        "https://blog.jetbrains.com/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "the_new_stack",
        "The New Stack",
        "https://thenewstack.io/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tianhe_gao",
        "Tianhe Gao",
        "https://tianheg.co/index.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tw93_blog",
        "Tw93 Blog",
        "https://tw93.fun/feed.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "usubeni_fantasy",
        "Usubeni Fantasy",
        "https://ssshooter.com/rss.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "vercel_news",
        "Vercel News",
        "https://vercel.com/atom",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "weishu_s_notes",
        "Weishu's Notes",
        "https://weishu.me/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "yiran_s_blog",
        "Yiran's Blog",
        "https://zdyxry.github.io/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "s_blog",
        "东东's Blog",
        "https://blog.yasking.org/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_066",
        "二丫讲梵",
        "https://wiki.eryajf.net/rss.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "the_coding_life__no_wine__no",
        "农码生涯，无酒无花 – The coding life, no wine, no shine.",
        "https://nicrosoft.net/blog/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_068",
        "千里之豪的格物垛",
        "https://blog.gadore.top/feed.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_069",
        "卡瓦邦噶！",
        "https://www.kawabangga.com/feed",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_070",
        "后端技术杂谈",
        "https://rowkey.cn/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_071",
        "唐巧的博客",
        "https://blog.devtang.com/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_072",
        "喵喵小站・博客志",
        "https://www.mmbkz.cn/feed",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_073",
        "夜法之书",
        "https://blog.17lai.site/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_074",
        "如有乐享",
        "https://51.ruyo.net/feed",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_075",
        "寒夜雨",
        "https://www.coderlock.site/index.php/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "heo",
        "张洪Heo",
        "https://blog.zhheo.com/rss.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_077",
        "张鑫旭-鑫空间-鑫生活",
        "http://www.zhangxinxu.com/wordpress/?feed=rss2",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_078",
        "愆伏",
        "https://www.tortorse.com/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "iconpik",
        "王圆圆 - ICONPIK",
        "https://www.iconpik.com/rss/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_080",
        "王福强的个人博客：一个架构士的思考与沉淀",
        "https://afoo.me/feeds.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_081",
        "皓子的小站",
        "https://howiehz.top/rss.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_082",
        "粥里有勺糖",
        "https://sugarat.top/feed.rss",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_083",
        "维基萌",
        "https://www.wikimoe.com/rss.php",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "ai",
        "老范讲故事｜AI、大模型与商业世界的故事",
        "http://lukefan.com/?feed=rss2",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_085",
        "胡涂说",
        "https://hutusi.com/feed.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_086",
        "虹墨空间站",
        "https://www.imaegoo.com/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_087",
        "豌豆花下猫",
        "https://pythoncat.top/rss.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_088",
        "阁子",
        "https://dfine.tech/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_089",
        "鸟窝",
        "https://colobu.com/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_090",
        "黑羽的个人博客",
        "https://blog.thetbw.xyz/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "cisa",
        "CISA",
        "https://www.cisa.gov/news.xml",
        "security",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "freebuf",
        "FreeBuf 网络安全行业门户",
        "https://www.freebuf.com/feed",
        "security",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "krebs_on_security",
        "Krebs on Security",
        "https://krebsonsecurity.com/feed/",
        "security",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "schneier_on_security",
        "Schneier on Security",
        "https://www.schneier.com/blog/index.rdf",
        "security",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "security_affairs",
        "Security Affairs",
        "https://securityaffairs.co/wordpress/feed",
        "security",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "zdnet_security",
        "ZDNET Security",
        "https://www.zdnet.com/topic/security/rss.xml",
        "security",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_097",
        "安全客",
        "https://api.anquanke.com/data/v1/rss",
        "security",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_098",
        "腾讯玄武实验室",
        "https://wechat2rss.xlab.app/feed/923c0e2f33b6d39c8a826a90f185725f0edb10e8.xml",
        "security",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "36",
        "36氪",
        "https://www.36kr.com/feed",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "ars_technica",
        "Ars Technica",
        "https://feeds.arstechnica.com/arstechnica/index",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "engadget",
        "Engadget",
        "https://www.engadget.com/rss.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "it",
        "IT之家",
        "https://www.ithome.com/rss/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "mit_technology_review",
        "MIT Technology Review",
        "https://www.technologyreview.com/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "techcrunch",
        "TechCrunch",
        "https://techcrunch.com/feed/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "the_verge___news",
        "The Verge — News",
        "https://www.theverge.com/rss/index.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "wired",
        "WIRED",
        "https://www.wired.com/feed/rss",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_107",
        "少数派",
        "https://sspai.com/feed",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_108",
        "爱范儿",
        "https://www.ifanr.com/feed",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "aigc_weekly",
        "AIGC Weekly",
        "https://quaily.com/op7418/feed/atom",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "golang_weekly",
        "Golang Weekly",
        "https://golangweekly.com/rss/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "javascript_weekly",
        "JavaScript Weekly",
        "https://javascriptweekly.com/rss/",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "last_week_in_ai",
        "Last Week in AI",
        "https://lastweekin.ai/feed",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "the_batch",
        "The Batch",
        "https://rsshub.bestblogs.dev/deeplearning/the-batch",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "this_week_in_rust",
        "This Week in Rust",
        "https://this-week-in-rust.org/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_115",
        "潮流周刊",
        "https://weekly.tw93.fun/rss.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_116",
        "阮一峰的网络日志",
        "https://www.ruanyifeng.com/blog/atom.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "aaas__science__table_of_contents",
        "AAAS: Science: Table of Contents",
        "https://www.science.org/action/showFeed?type=etoc&amp;feed=rss&amp;jc=science",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "bbc_news___science",
        "BBC News — Science",
        "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "elife__latest_articles",
        "eLife: latest articles",
        "https://elifesciences.org/rss/recent.xml",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "flowingdata",
        "FlowingData",
        "https://flowingdata.com/feed",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "nasa",
        "NASA",
        "https://www.nasa.gov/news-release/feed/",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "nature",
        "Nature",
        "https://www.nature.com/nature.rss",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "nyt___science",
        "NYT > Science",
        "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "phys_org___latest_science_and_technology",
        "Phys.org - latest science and technology news stories",
        "https://phys.org/rss-feed/",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "plos_one",
        "PLOS One",
        "https://journals.plos.org/plosone/feed/atom",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "quanta_magazine",
        "Quanta Magazine",
        "https://www.quantamagazine.org/feed/",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "scientific_american_content__global",
        "Scientific American Content: Global",
        "http://rss.sciam.com/ScientificAmerican-Global",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "space___the_guardian",
        "Space | The Guardian",
        "https://www.theguardian.com/science/space/rss",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "space___latest_in_science_and_technology",
        "Space – latest in science and technology | New Scientist",
        "https://www.newscientist.com/subject/space/feed/",
        "science",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "al_jazeera___breaking_news__world_news_a",
        "Al Jazeera – Breaking News, World News and Video from Al Jazeera",
        "https://www.aljazeera.com/xml/rss/all.xml",
        "world news",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "bbc_news___news",
        "BBC News — News",
        "https://feeds.bbci.co.uk/news/world/rss.xml",
        "world news",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "cointelegraph_com_news",
        "Cointelegraph.com News",
        "https://cointelegraph.com/rss/tag/blockchain",
        "world news",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "infoq___news",
        "InfoQ — News",
        "https://feed.infoq.com/",
        "world news",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "npr_topics__world",
        "NPR Topics: World",
        "https://feeds.npr.org/1004/rss.xml",
        "world news",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "nyt___technology",
        "NYT > Technology",
        "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
        "world news",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "propublica",
        "ProPublica",
        "https://www.propublica.org/feeds/propublica/main",
        "world news",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "world_news___the_guardian",
        "World news | The Guardian",
        "https://www.theguardian.com/world/rss",
        "world news",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "solidot",
        "奇客Solidot–传递最新科技情报",
        "https://www.solidot.org/index.rss",
        "world news",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_139",
        "虎嗅",
        "https://rss.huxiu.com/",
        "world news",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_140",
        "钛媒体：引领未来商业与生活新知",
        "https://www.tmtpost.com/feed",
        "world news",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "61_s_life",
        "61’s life",
        "https://61.life/feed.xml",
        "design",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "jax",
        "jax",
        "https://cdjax.com/?feed=rss2",
        "design",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "velas",
        "Velas电波站",
        "https://www.velasx.com/feed",
        "design",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_144",
        "拾月的博客",
        "https://www.skyue.com/feed/",
        "design",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_145",
        "阿里云设计中心",
        "https://wechat2rss.xlab.app/feed/31e04606d37f684059e23a8fd3e05f1db0186495.xml",
        "design",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "macin",
        "Macin",
        "https://www.macin.org/atom.xml",
        "business",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_147",
        "知足常乐-水星投资理财的基本意念",
        "http://mercurychong.blogspot.com/feeds/posts/default",
        "business",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_148",
        "虹线",
        "https://1q43.blog/feed",
        "business",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_149",
        "雷蒙三十｜幫助忙碌現代人的聰明工作、好好生活的生產力指南",
        "https://raymondhouch.com/feed",
        "business",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "abb00717",
        "ABB00717",
        "https://blog.abb00717.com/index.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "another_dayu",
        "Another Dayu",
        "https://anotherdayu.com/feed/",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "dort",
        "Dort 的博客",
        "https://blog.dort.me/rss.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "happy_xiao",
        "happy xiao",
        "https://happyxiao.com/feed",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "jake_blog",
        "Jake blog",
        "https://jaketao.com/feed/",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "jame",
        "Jame",
        "https://jame.work/feed.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "justzht_s_echochamber",
        "JustZht's EchoChamber",
        "https://www.justzht.com/rss/",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "m_x_chris_an_emacser",
        "M-x Chris-An-Emacser",
        "https://chriszheng.science/atom.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "seisamuse",
        "SEISAMUSE",
        "https://www.seis-jun.xyz/atom.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "shuibaco",
        "Shuibaco • 水八口",
        "https://shuiba.co/feed",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "wsh",
        "WSH",
        "https://www.wsh233.cn/feed.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "blog",
        "一派胡言 · Blog",
        "https://yipai.me/feed",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_162",
        "不吐不快",
        "https://mianao.info/atom.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_163",
        "卢昌海个人主页",
        "https://www.changhai.org/feed.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_164",
        "印记",
        "https://yinji.org/feed",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_165",
        "四喜丸子",
        "https://fourhappylions.com/index.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_166",
        "如鱼饮水",
        "https://wangjiezhe.com/atom.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_167",
        "局域自由博客",
        "https://localfreedom.pages.dev/index.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_168",
        "廊桥遗梦",
        "https://blog.moran.im/rss.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_169",
        "梅之夏",
        "https://blog.mcenahle.page/feed.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_170",
        "涵哲子居",
        "https://iluc.cn/rss.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_171",
        "祝融说。",
        "https://zhurongshuo.com/index.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "jn",
        "資工小廢物 - JN",
        "https://blog.giveanornot.com/index.xml",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "life",
        "闲人LIFE",
        "https://www.xianrenlife.com/feeds/posts/default",
        "blogs",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "hacker_news",
        "Hacker News",
        "https://news.ycombinator.com/rss",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "linux_do",
        "LINUX DO · 文档共建",
        "https://linuxdorss.longpink.com/wiki.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "lobsters",
        "Lobsters",
        "https://lobste.rs/rss",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "nixos_development",
        "NixOS Development",
        "https://discourse.nixos.org/c/dev/14.rss?order=created",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "v2ex",
        "V2EX · 技术",
        "https://www.v2ex.com/feed/tab/tech.xml",
        "technology",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "kaix_in",
        "KAIX.IN",
        "https://kaix.in/feed/",
        "entertainment",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "maohang_gao_s_blog",
        "Maohang Gao's Blog",
        "https://kangaroogao.com/atom.xml",
        "entertainment",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "shinekid",
        "ShineKid",
        "https://shinekid.com/feed/",
        "entertainment",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tripper_press___take_photo__think_seriou",
        "Tripper Press - Take Photo, Think Seriously.",
        "https://tripper.press/atom.xml",
        "entertainment",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_183",
        "东评西就",
        "https://dongjunke.cn/atom.xml",
        "entertainment",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_184",
        "先生制造",
        "https://wechat2rss.xlab.app/feed/313326d41db4f54b1cc09e7c986a5ac4e5f88ca0.xml",
        "entertainment",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_185",
        "赫赫文王",
        "https://kqh.me/index.xml",
        "entertainment",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_186",
        "静风说",
        "http://www.jfsay.com/feed",
        "entertainment",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "3blue1brown",
        "3Blue1Brown",
        "https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw",
        "media",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "y_combinator",
        "Y Combinator",
        "https://www.youtube.com/feeds/videos.xml?channel_id=UCcefcZRL2oaA_uBNeo5UOWg",
        "media",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "darknet_diaries",
        "Darknet Diaries",
        "https://feeds.megaphone.fm/darknetdiaries",
        "media",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "hanselminutes_with_scott_hanselman",
        "Hanselminutes with Scott Hanselman",
        "https://feeds.simplecast.com/gvtxUiIf",
        "media",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "invest_like_the_best_with_patrick_o_shau",
        "Invest Like the Best with Patrick O'Shaughnessy",
        "https://investlikethebest.libsyn.com/rss",
        "media",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "what_s_next",
        "What's Next｜科技早知道",
        "https://rsshub.bestblogs.dev/xiaoyuzhou/podcast/5e74b52c418a84a046ecaceb",
        "media",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_193",
        "半拿铁 | 商业沉浮录",
        "https://rsshub.bestblogs.dev/xiaoyuzhou/podcast/62382c1103bea1ebfffa1c00",
        "media",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_194",
        "声动早咖啡",
        "https://rsshub.bestblogs.dev/xiaoyuzhou/podcast/60de7c003dd577b40d5a40f3",
        "media",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_195",
        "忽左忽右",
        "https://rsshub.bestblogs.dev/xiaoyuzhou/podcast/5e4ee557418a84a0466737b7",
        "media",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_196",
        "文化有限",
        "https://rsshub.bestblogs.dev/xiaoyuzhou/podcast/5e4515bd418a84a046e2b11a",
        "media",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "latetalk",
        "晚点聊 LateTalk",
        "https://rsshub.bestblogs.dev/xiaoyuzhou/podcast/61933ace1b4320461e91fd55",
        "media",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "tidings_198",
        "知行小酒馆",
        "https://rsshub.bestblogs.dev/xiaoyuzhou/podcast/6013f9f58e2f7ee375cf4216",
        "media",
        "tidings_rss",
        tier=2,
    ),
    _rss(
        "101___podcast",
        "硅谷101 — Podcast",
        "https://rsshub.bestblogs.dev/xiaoyuzhou/podcast/5e5c52c9418a84a04625e6cc",
        "media",
        "tidings_rss",
        tier=2,
    ),
]


COLLECTOR_SOURCES_BY_GROUP: Dict[str, List[SourceSpec]] = {}
SOURCE_BY_KEY: Dict[str, SourceSpec] = {}

for source in COLLECTOR_SOURCES:
    SOURCE_BY_KEY[source.key] = source
    if source.collector:
        COLLECTOR_SOURCES_BY_GROUP.setdefault(source.collector, []).append(source)


def get_collector_sources(group: str) -> List[SourceSpec]:
    """Return sources used by a collector group."""
    return list(COLLECTOR_SOURCES_BY_GROUP.get(group, []))


def get_health_sources() -> List[SourceSpec]:
    """Return all sources for health checks."""
    return list(COLLECTOR_SOURCES)